server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

polar:
  greeting: welcome to the local book catalog!
spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: catalog-service
  datasource:
      username: hoonseung
      password: 4617
      url: jdbc:postgresql://localhost:5432/polardb_catalog
      hikari:
        connection-timeout: 2000
        maximum-pool-size: 5
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # 재시도 작동
      retry:
        max-attempts: 6 # 최대 시도수
        initial-interval: 1000 # 최초 재시도 지연 시간 (밀리초)
        max-interval: 2000 # 재시도 지연 최대 시간
        multiplier: 1.1 # 지연 시간 계산 승수
  flyway:
    baseline-on-migrate: true
    locations: "classpath:db/migration"

management:
  endpoints:
    web:
      exposure:
        include: refresh
