apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: # 커스터마이즈가 관리하고 처리할 쿠버네티스트 매니페스트
  - deployment.yml
  - service.yml


configMapGenerator: # 컨피그맵 생성
  - name: catalog-config
    files: # 같은 경로에 있는 yaml 파일 이름
      - application.yml
    options:
      labels:
        app: catalog-service


